services:
  - type: web
    name: socialblaster-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: .